TS=20ms
;protocol body - generated by wizard
;version ZB June 11, 2010
include default.inc  ;Includes standard options, do not remove it !
include light.inc  ;Includes standard options, do not remove it !
include microscope.inc  ;Includes standard options, do not remove it !
include extralight.inc  ;Includes standard options, do not remove it !
;
FlashUV=0
FlashBlue=100
FlashGreen=0
FlashWH=0
FlashRed=0
ActinicUV=0
ActinicBlue=50
ActinicGreen=0
ActinicWH=0
ActinicRed=0
Far=0
Super=50
Act1=100
Sensitivity=50
Shutter=0
;
;-------------------------------------------------------------------------------------------------------------
;*** Light settings ******************************************************************************************
;-------------------------------------------------------------------------------------------------------------
;
<TS>=>SETLIGHT(0,1,0,0,0,0,1,0,0,0) ; command for enabling Light2
;************************************
;***********************************
;**************************************
;***************************************
;________________________________________________________________________
;
;-------------------------------------------------------------------------------------------------------------
;*** Fo Measurement ******************************************************************************************
;-------------------------------------------------------------------------------------------------------------
start=TS + TS
F0duration=1s
F0period=100ms
PulseDuration=800ms;
;
<0s>=>actinic_on(start + F0duration + 2*mfmsub_length + PulseDuration + mfmsub_length)
;
<start, start + F0period .. start + F0duration + TS>=>mfmsub
;
<start + mfmsub_length>=>checkPoint,"startFo"
<start + F0duration - mfmsub_length>=>checkPoint,"endFo"
;
;
;-------------------------------------------------------------------------------------------------------------
;*** Saturating Pulse & Fm Measurement ***********************************************************************
;-------------------------------------------------------------------------------------------------------------
;    ##   
a= start + F0duration + 2*mfmsub_length;   ##
;
<a>=>SUPER_ON
<a + PulseDuration>=>SUPER_OFF
<a + TS, a + TS + mfmsub_length..a + PulseDuration>=>mfmsub
;
<a + PulseDuration + mfmsub_length>=>mfmsub
;
;Fm definition
<a + PulseDuration/3>=>checkPoint,"startFm"
<a + PulseDuration - mfmsub_length>=>checkPoint,"endFm"
;
;Visual frame definition                                                - image shown in pre-processing window
<a + PulseDuration/2 + mfmsub_length>=>checkPoint,"timeVisual"
;
;END ******************************************************************
