TS=20ms
;protocol body - generated by wizard
;version ZB 2011 June 16
include default.inc  ;Includes standard options, do not remove it !
include qa.inc;    ;Include qa command,do not remove it !
Shutter=0
Sensitivity=30
;
pause = 1s
;
;**********************************************************************
;
Action QA_sample(delay) begin
  measure_delay = trunc((0.5+1000000*delay) div 20000)
  flash_delay = trunc(1000000*delay - measure_delay*20000)/1000000
  <0s>=>QA(100us,flash_delay)   ;delay in us
  <TS>=>bit0H      
  <measure_delay*TS+2*TS>=>fm 
end
;***********************************************************************
;
TimeAxis =<1us,10us,13us,18us,24us,32us,42us,56us,75us,100us,133us,178us,237us,316us,422us,562us,750us,1000us,1334us,1778us,2371us,3162us,4217us,5623us,7499us,10000us,13335us,17783us,23714us,31623us,42170us,56234us,74989us,100000us,133352us,177828us,237137us,316228us,421697us,562341us,749894us,1000ms>
;
<1us>=>checkPoint,"startFo"
<10us>=>checkPoint,"startFm"
<13us>=>checkPoint,"timeVisual"
;
;***********************************************************************
<0s>=>fm
;
b = 2*TS
;
<b>=>QA_sample(100us + 10us)
<b+pause*1>=>QA_sample(100us + 13us)
<b+pause*2>=>QA_sample(100us + 18us)
<b+pause*3>=>QA_sample(100us + 24us)
<b+pause*4>=>QA_sample(100us + 32us)
<b+pause*5>=>QA_sample(100us + 42us)
<b+pause*6>=>QA_sample(100us + 56us)
<b+pause*7>=>QA_sample(100us + 75us)
<b+pause*8>=>QA_sample(100us + 100us)
<b+pause*9>=>QA_sample(100us + 133us)
<b+pause*10>=>QA_sample(100us + 178us)
<b+pause*11>=>QA_sample(100us + 237us)
<b+pause*12>=>QA_sample(100us + 316us)
<b+pause*13>=>QA_sample(100us + 422us)
<b+pause*14>=>QA_sample(100us + 562us)
<b+pause*15>=>QA_sample(100us + 750us)
<b+pause*16>=>QA_sample(100us + 1000us)
<b+pause*17>=>QA_sample(100us + 1334us)
<b+pause*18>=>QA_sample(100us + 1778us)
<b+pause*19>=>QA_sample(100us + 2371us)
<b+pause*20>=>QA_sample(100us + 3162us)
<b+pause*21>=>QA_sample(100us + 4217us)
<b+pause*22>=>QA_sample(100us + 5623us)
<b+pause*23>=>QA_sample(100us + 7499us)
<b+pause*24>=>QA_sample(100us + 10000us)
<b+pause*25>=>QA_sample(100us + 13335us)
<b+pause*26>=>QA_sample(100us + 17783us)
<b+pause*27>=>QA_sample(100us + 23714us)
<b+pause*28>=>QA_sample(100us + 31623us)
<b+pause*29>=>QA_sample(100us + 42170us)
<b+pause*30>=>QA_sample(100us + 56234us)
<b+pause*31>=>QA_sample(100us + 74989us)
<b+pause*32>=>QA_sample(100us + 100000us)
<b+pause*33>=>QA_sample(100us + 133352us)
<b+pause*34>=>QA_sample(100us + 177828us)
<b+pause*35>=>QA_sample(100us + 237137us)
<b+pause*36>=>QA_sample(100us + 316228us)
<b+pause*37>=>QA_sample(100us + 421697us)
<b+pause*38>=>QA_sample(100us + 562341us)
<b+pause*39>=>QA_sample(100us + 749894us)
<b+pause*40>=>QA_sample(100us + 1000ms)
