TS=20ms
;protocol body - generated by wizard
;version ZB February 11, 2010
include default.inc  ;Includes standard options, do not remove it !
include light.inc    ;Includes standard options, do not remove it !
Shutter=3
Sensitivity=52
Act1=100
Super=100

;
;------------------------------------------------------------------------------------------------------------
;************************************************************************************************************
Action SATPULSE begin
  <-mfmsub_length>=>mfmsub ;before pulse
  <0s>=>SatPulse(800ms)
  <TS,TS + 2 * mfmsub_length .. 800ms/2 - mfmsub_length>=>mfmsub
  <800ms/2,800ms/2 + mfmsub_length .. 800ms>=>mfmsub
  <800ms + mfmsub_length>=>mfmsub
end
;
Action MEASURE(end_time) begin
  <800ms + 2*mfmsub_length,800ms + 2*mfmsub_length + 130 * mfmsub_length ..end_time - mfmsub_length>=>mfmsub
end

;Action MEASURE(end_time) begin
;  <800ms + 2*mfmsub_length,800ms + 2*mfmsub_length + 40 * mfmsub_length ..end_time - mfmsub_length>=>mfmsub
;end
;
Action FARREDILL(end_time) begin
  <800ms + 4*mfmsub_length,800ms + 4*mfmsub_length + 40 * mfmsub_length ..end_time - 2 * mfmsub_length>=>FAR(38*mfmsub_length)
end
;-------------------------------------------------------------------------------------------------------------
;*** Fo Measurement ******************************************************************************************
;-------------------------------------------------------------------------------------------------------------
F0duration=120s
F0period=1s
;
<0, F0period  .. F0duration>=>mfmsub
<F0duration - F0period>=>checkPoint,"startFo_Lss"
<F0duration>=>checkPoint,"endFo_Lss"
;
;-------------------------------------------------------------------------------------------------------------
;*** Saturating Pulse & Fm Measurement ***********************************************************************
;-------------------------------------------------------------------------------------------------------------
PulseDuration = 800ms;      ##
PulseStart = F0duration + 2*TS;      ##
;
<PulseStart>=>SATPULSE
<PulseStart>=>act1(PulseDuration)
;
<PulseStart + PulseDuration/2>=>checkPoint,"startFm_Lss"
<PulseStart + PulseDuration - mfmsub_length>=>checkPoint,"endFm_Lss"
;
;Visual frame definition                                                  Image shown in pre-processing window
<PulseStart + PulseDuration - 3*mfmsub_length>=>checkPoint,"timeVisual"
;
;-------------------------------------------------------------------------------------------------------------
;******* Dark Relaxation Measurement *************************************************************************
;-------------------------------------------------------------------------------------------------------------
DarkRelaxation1 = 10s;         ##
DarkStart= PulseStart + PulseDuration + 2*mfmsub_length; ##
;
<DarkStart, DarkStart + mfmsub_length *10..DarkStart + DarkRelaxation1 - 2*mfmsub_length>=>mfmsub

;******* Saturating Pulses in Dark- Fm_D'********************************************************************
;
pd1 = DarkStart + 11s
pd2 = pd1 + 144.5s
pd3 = pd2 + 64.5s
pd4 = pd3 + 96.2s
;pulse 1
<pd1>=>SATPULSE
<pd1>=>act1(PulseDuration)
<pd1 - mfmsub_length>=>checkPoint,"startFt_D1"
<pd1 + PulseDuration/2>=>checkPoint,"startFm_D1"
<pd1 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D1"
;from 1 to 2
<pd1>=>MEASURE(pd2 - pd1)
;2
<pd2>=>SATPULSE
<pd2>=>act1(PulseDuration)
<pd2 - mfmsub_length>=>checkPoint,"startFt_D2"
<pd2 + PulseDuration/2>=>checkPoint,"startFm_D2"
<pd2 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D2"
;from 2 to 3
<pd2>=>MEASURE(pd3 - pd2)
;3
<pd3>=>SATPULSE
<pd3>=>act1(PulseDuration)
<pd3 - mfmsub_length>=>checkPoint,"startFt_D3"
<pd3 + PulseDuration/2>=>checkPoint,"startFm_D3"
<pd3 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D3"
;from 3 to 4
<pd3 + PulseDuration>=>MEASURE(pd4 - pd3)
;4
<pd4>=>SATPULSE
<pd4 - mfmsub_length>=>checkPoint,"startFt_D4"
<pd4 + PulseDuration/2>=>checkPoint,"startFm_D4"
<pd4 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D4"

FoMeasureStart=pd4 + PulseDuration + 2*mfmsub_length
FoPeriod=10s

<FoMeasureStart>=>MEASURE(FoPeriod)
<FoMeasureStart>=>FARREDILL(FoPeriod)

FoPrimeStart=FoMeasureStart+FoPeriod
<FoPrimeStart - 2*TS>=>checkPoint,"startFoPrime"
<FoPrimeStart>=>checkPoint,"endFoPrime"
;;;;;;
;end