TS=50ms
;protocol body - generated by wizard
;version ZB February 11, 2010
include default.inc  ;Includes standard options, do not remove it !
include light.inc    ;Includes standard options, do not remove it !
Shutter=3
Sensitivity=52
Act1=100
Super=100

pl1 = 24.8 s
pl2 = 151.1 s
pl3 = 277.5 s
pl4 = 403.8 s
pd1 = 414.8 s
pd2 = 559.3 s
pd3 = 703.8 s
pd4 = 800.0 s

;
;------------------------------------------------------------------------------------------------------------
;************************************************************************************************************
Action SATPULSE begin
  <-mfmsub_length>=>mfmsub ;before pulse
  <0s>=>SatPulse(800ms)
  <TS,TS + 2 * mfmsub_length .. 800ms/2 - mfmsub_length>=>mfmsub
  <800ms/2,800ms/2 + mfmsub_length .. 800ms>=>mfmsub
  <800ms + mfmsub_length>=>mfmsub
end
;
Action MEASURE(end_time) begin
  <800ms + 2*mfmsub_length,800ms + 2*mfmsub_length + 130 * mfmsub_length ..end_time - mfmsub_length>=>mfmsub
end
;-------------------------------------------------------------------------------------------------------------
;*** Fo Measurement ******************************************************************************************
;-------------------------------------------------------------------------------------------------------------
F0duration=5s
F0period = mfmsub_length * 5
;
<0, F0period  .. F0duration>=>mfmsub
<F0period>=>checkPoint,"startFo"
<F0duration - F0period>=>checkPoint,"endFo"
;
;-------------------------------------------------------------------------------------------------------------
;*** Saturating Pulse & Fm Measurement ***********************************************************************
;-------------------------------------------------------------------------------------------------------------
PulseDuration = 800ms;      ##
PulseStart = F0duration + 2*mfmsub_length;      ##
;
<PulseStart>=>SATPULSE
<PulseStart>=>act1(PulseDuration)
;
<PulseStart + PulseDuration/2>=>checkPoint,"startFm"
<PulseStart + PulseDuration - mfmsub_length>=>checkPoint,"endFm"
;
;Visual frame definition                                                  Image shown in pre-processing window
<PulseStart + PulseDuration - 3*mfmsub_length>=>checkPoint,"timeVisual"
;
;-------------------------------------------------------------------------------------------------------------
;******* Dark Relaxation Measurement *************************************************************************
;-------------------------------------------------------------------------------------------------------------
DarkRelaxation1 = 10s;         ##
DarkStart= PulseStart + PulseDuration + 2*mfmsub_length; ##
;
<DarkStart, DarkStart + mfmsub_length *10..DarkStart + DarkRelaxation1 - 2*mfmsub_length>=>mfmsub
;
;-------------------------------------------------------------------------------------------------------------
;******* Kautsky Effect Measurement **************************************************************************
;-------------------------------------------------------------------------------------------------------------
;
;******* Actinic light Exposure **************************************
ALPeriod = 390s + TS;            ##
ALStart = 15.8s;##
EndFp = 20.3s
;
<ALStart - TS>=>act1(ALPeriod)
;
;*******Fast Kautsky kinetics*****************************************
<ALStart - 2*mfmsub_length>=>mfmsub
<ALStart, ALStart + mfmsub_length .. EndFp - 2*mfmsub_length>=>mfmsub
;
;Fp definition
<ALStart>=>checkPoint,"startFp"
<EndFp>=>checkPoint,"endFp"
;
;*******Slow Kautsky kinetics*********************************************
;
; measure to pulse 1
<EndFp,EndFp + 130 * mfmsub_length..pl1 - 2*mfmsub_length>=>mfmsub
; measure from last pulse
<pl4 + PulseDuration + 2*mfmsub_length,pl4 + PulseDuration + 2*mfmsub_length + 130 * mfmsub_length .. ALStart + ALPeriod - mfmsub_length>=>mfmsub
<ALStart + ALPeriod - mfmsub_length>=>mfmsub
;
;-------------------------------------------------------------------------------------------------------------
;******* Saturating Pulses - Fm' Quenching Analysis **********************************************************
;-------------------------------------------------------------------------------------------------------------
;
;******* Saturating Pulses in Light- Fm_L'********************************************************************


;pulse 1
<pl1>=>SATPULSE
<pl1 - mfmsub_length>=>checkPoint,"startFt_L1"
<pl1 + PulseDuration/2>=>checkPoint,"startFm_L1"
<pl1 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_L1"
;
;1 to 2 pulses
<pl1>=>MEASURE(pl2 - pl1)
;2 pulses
<pl2>=>SATPULSE
<pl2 - mfmsub_length>=>checkPoint,"startFt_L2"
<pl2 + PulseDuration/2>=>checkPoint,"startFm_L2"
<pl2 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_L2"
;
;2 to 3 pulses
<pl2>=>MEASURE(pl3 - pl2)
;3
<pl3>=>SATPULSE
<pl3 - mfmsub_length>=>checkPoint,"startFt_L3"
<pl3 + PulseDuration/2>=>checkPoint,"startFm_L3"
<pl3 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_L3"
;
;from 3 to 4
<pl3>=>MEASURE(pl4 - pl3)
;4
<pl4>=>SATPULSE
<pl4 - mfmsub_length>=>checkPoint,"startFt_Lss"
<pl4 + PulseDuration/2>=>checkPoint,"startFm_Lss"
<pl4 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_Lss"
;\
;
;-------------------------------------------------------------------------------------------------------------
;******* Dark relaxation after actinic light period **********************************************************
;-------------------------------------------------------------------------------------------------------------
DarkRelaxation2 = 300s
;
; measure to pulse 1
<ALStart + ALPeriod, ALStart + ALPeriod + 130 * mfmsub_length..pd1 - 2*mfmsub_length>=>mfmsub
; measure from last pulse
<703.8 + PulseDuration + 2*mfmsub_length, pd3 + PulseDuration + 2*mfmsub_length + 130 * mfmsub_length..ALStart + ALPeriod + DarkRelaxation2 - mfmsub_length>=>mfmsub
;<ALStart + ALPeriod + DarkRelaxation2>=>mfmsub
;
;******* Saturating Pulses in Dark- Fm_D'********************************************************************
;
;pulse 1
<pd1>=>SATPULSE
<pd1>=>act1(PulseDuration)
<pd1 - mfmsub_length>=>checkPoint,"startFt_D1"
<pd1 + PulseDuration/2>=>checkPoint,"startFm_D1"
<pd1 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D1"
;from 1 to 2
<pd1>=>MEASURE(pd2 - pd1)
;2
<pd2>=>SATPULSE
<pd2>=>act1(PulseDuration)
<pd2 - mfmsub_length>=>checkPoint,"startFt_D2"
<pd2 + PulseDuration/2>=>checkPoint,"startFm_D2"
<pd2 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D2"
;from 2 to 3
<pd2>=>MEASURE(pd3 - pd2)
;3
<pd3>=>SATPULSE
<pd3>=>act1(PulseDuration)
<pd3 - mfmsub_length>=>checkPoint,"startFt_D3"
<pd3 + PulseDuration/2>=>checkPoint,"startFm_D3"
<pd3 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D3"

;from 3 to 4
<pd3 + PulseDuration>=>MEASURE(pd4 - pd3)
;4
<pd4>=>SATPULSE
<pd4 - mfmsub_length>=>checkPoint,"startFt_D4"
<pd4 + PulseDuration/2>=>checkPoint,"startFm_D4"
<pd4 + PulseDuration - mfmsub_length>=>checkPoint,"endFm_D4"


FoMeasureStart=pd4 + PulseDuration + 2*mfmsub_length
FoPeriod=10s

<FoMeasureStart>=>MEASURE(FoPeriod)
<FoMeasureStart>=>FARREDILL(FoPeriod)

FoPrimeStart=FoMeasureStart+FoPeriod
<FoPrimeStart - 2*TS>=>checkPoint,"startFt_D5"
<FoPrimeStart>=>checkPoint,"startFt_D5"
;;;;;;
;end
