;protocol body - generated by wizard
;version PK June 17, 2008
include default.inc  ;Includes standard options, do not remove it !
include light.inc  ;Includes standard options, do not remove it !
ElectronicShutter=1
Sensitivity=60
Actinic=100
Super=100

<0,10s .. 90s - mfmsub_length>=>mfmsub
<0s>=>checkPoint,"startFo"

<100s>=>SatPulse(800ms)
<100s>=>actinlightOn(800ms)
<100s>=>mpulse
<100s + 400ms>=>checkPoint,"startFm"
<100s + 600ms>=>checkPoint,"timeVisual"
<100s + 800ms - mfmsub_length>=>checkPoint,"endFm"

<101s>=>mfmsub
<102s>=>mfmsub
<103s>=>mfmsub

