;protocol body - generated by wizard
;version PK June 24, 2005
include default.inc  ;Includes standard options, do not remove it !
include light.inc  ;Includes standard options, do not remove it !
ElectronicShutter=1
Sensitivity=61
Actinic=57
Super=90
;
;this is Fo definition
;
<0,1s .. 5s - 2*mfmsub_length>=>mfmsub
<0s>=>checkPoint,"startFo"
<5s - 2*mfmsub_length>=>checkPoint,"endFo"
;
;this saturation pulse Fm measurement
;
<5s>=>SatPulse(800ms)
<5s>=>actinlightOn(800ms)
<5s>=>mpulse
<5s + 800ms/2>=>checkPoint,"startFm"
<5s + 600ms>=>checkPoint,"timeVisual"
<5s + 800ms - mfmsub_length>=>checkPoint,"endFm"
;
;dark pause
;
<7s, 7s + 1s .. 15s - mfmsub_length>=>mfmsub
;
;actinic light definition
;
<15s>=>actinlightOn(1800s)
;
;saturating pulses in Kautsky induction and Dark relaxation
;
<15s, 15s + 3s .. 24s - 2*mfmsub_length>=>mfmsub
<24s - mfmsub_length>=>checkPoint,"startFt_L1"
<24s>=>SatPulse(800ms)
<24s>=>mpulse
<24s + 400ms>=>checkPoint,"startFm_L1"
<24s + 800ms - mfmsub_length>=>checkPoint,"endFm_L1"

<25s, 25s + 30s .. 471s - 2*mfmsub_length>=>mfmsub
<471s - mfmsub_length>=>checkPoint,"startFt_L2"
<471s>=>SatPulse(800ms-20ms)
<471s>=>mpulse
<471 + 400ms>=>checkPoint,"startFm_L2"
<471 + 800ms - mfmsub_length>=>checkPoint,"endFm_L2"

<472s, 472s + 30s .. 918s - 2*mfmsub_length>=>mfmsub
<918s - mfmsub_length>=>checkPoint,"startFt_L3"
<918s>=>SatPulse(800ms)
<918s>=>mpulse
<918s + 400ms>=>checkPoint,"startFm_L3"
<918s + 800ms - mfmsub_length>=>checkPoint,"endFm_L3"

<919s, 919s + 30s .. 1365s - 2*mfmsub_length>=>mfmsub
<1365s - mfmsub_length>=>checkPoint,"startFt_L4"
<1365s>=>SatPulse(800ms)
<1365s>=>mpulse
<1365s + 400ms>=>checkPoint,"startFm_L4"
<1365s + 800ms - mfmsub_length>=>checkPoint,"endFm_L4"

<1366, 1366s + 30s .. 1812s - 2*mfmsub_length>=>mfmsub
<1812s + mfmsub_length>=>checkPoint,"startFt_Lss"
<1812s>=>SatPulse(800ms)
<1812s>=>mpulse
<1812s+ 400ms>=>checkPoint,"startFm_Lss"
<1812s + 800ms - mfmsub_length>=>checkPoint,"endFm_Lss"


