;protocol body - generated by wizard
;version PK June 24, 2005
include default.inc  ;Includes standard options, do not remove it !
include light.inc  ;Includes standard options, do not remove it !
ElectronicShutter=0
Sensitivity=60
Actinic=40
Super=50
;
;this is Fo definition
;
<0,1s .. 5s - mfmsub_length>=>mfmsub
<0s>=>checkPoint,"startFo"
<5s - 2*mfmsub_length>=>checkPoint,"endFo"
;
;this saturation pulse Fm measurement
;
<5s>=>SatPulse(800ms)
<5s>=>actinlightOn(800ms)
<5s>=>mpulse
<5s + 400ms>=>checkPoint,"startFm"
<5s + 600ms>=>checkPoint,"timeVisual"
<5s + 800ms - mfmsub_length>=>checkPoint,"endFm"
;
;dark pause
;
<6s, 6s + 10*mfmsub_length .. 16s - mfmsub_length>=>mfmsub
;
;actinic light definition
;
<16s>=>actinlightOn(61s)
;
;saturating pulses in Kautsky induction and Dark relaxation
;
<16s + mfmsub_length, 16s + mfmsub_length + 10*mfmsub_length .. 25s - 2*mfmsub_length>=>mfmsub
<21s>=>checkPoint,"startFp"

<25s - mfmsub_length>=>checkPoint,"startFt_L1"
<25s>=>SatPulse(800ms)
<25s>=>mpulse
<25s + 400ms>=>checkPoint,"startFm_L1"
<25s + 800ms - mfmsub_length>=>checkPoint,"endFm_L1"
<26s, 26s + 10*mfmsub_length .. 37s - 2*mfmsub_length>=>mfmsub

<37s - mfmsub_length>=>checkPoint,"startFt_L2"
<37s>=>SatPulse(800ms)
<37s>=>mpulse
<37s + 400ms>=>checkPoint,"startFm_L2"
<37s + 800ms - mfmsub_length>=>checkPoint,"endFm_L2"
<38s, 38s + 10*mfmsub_length .. 49s - 2*mfmsub_length>=>mfmsub

<49s - mfmsub_length>=>checkPoint,"startFt_L3"
<49s>=>SatPulse(800ms)
<49s>=>mpulse
<49s + 400ms>=>checkPoint,"startFm_L3"
<49s + 800ms - mfmsub_length>=>checkPoint,"endFm_L3"
<50s, 50s + 10*mfmsub_length .. 61s - 2*mfmsub_length>=>mfmsub

<61s - mfmsub_length>=>checkPoint,"startFt_L4"
<61s>=>SatPulse(800ms)
<61s>=>mpulse
<61s + 400ms>=>checkPoint,"startFm_L4"
<61s + 800ms - mfmsub_length>=>checkPoint,"endFm_L4"
<62s, 62s + 10*mfmsub_length .. 73s - 2*mfmsub_length>=>mfmsub

<73s - mfmsub_length>=>checkPoint,"startFt_Lss"
<73s>=>SatPulse(800ms)
<73s>=>mpulse
<73s + 400ms>=>checkPoint,"startFm_Lss"
<73s + 800ms - mfmsub_length>=>checkPoint,"endFm_Lss"
<74s, 74s + 10*mfmsub_length .. 85s - 2*mfmsub_length>=>mfmsub

<80s>=>checkPoint,"startFo_Lss"

<85s - mfmsub_length>=>checkPoint,"startFt_D1"
<85s>=>SatPulse(800ms)
<85s>=>mpulse
<85s + 400ms>=>checkPoint,"startFm_D1"
<85s + 800ms - mfmsub_length>=>checkPoint,"endFm_D1"
<86s, 86s + 10*mfmsub_length .. 97s - 2*mfmsub_length>=>mfmsub

<90s>=>checkPoint,"startFo_D1"

<97s  - mfmsub_length>=>checkPoint,"startFt_D2"
<97s>=>SatPulse(800ms)
<97s>=>mpulse
<97s + 400ms>=>checkPoint,"startFm_D2"
<97s + 800ms - mfmsub_length>=>checkPoint,"endFm_D2"
<98s, 98s + 10*mfmsub_length .. 109s - 2*mfmsub_length>=>mfmsub

<101s>=>checkPoint,"startFo_D2"

<109s - mfmsub_length>=>checkPoint,"startFt_D3"
<109s>=>SatPulse(800ms)
<109s>=>mpulse
<109s + 400ms>=>checkPoint,"startFm_D3"
<109s + 800ms  - mfmsub_length>=>checkPoint,"endFm_D3"
<110s, 110s + 10*mfmsub_length .. 121s - 2*mfmsub_length>=>mfmsub

<114s>=>checkPoint,"startFo_D3"

<121s - mfmsub_length>=>checkPoint,"startFt_D4"
<121s>=>SatPulse(800ms)
<121s>=>mpulse
<121s + 400ms>=>checkPoint,"startFm_D4"
<121s + 800ms - mfmsub_length>=>checkPoint,"endFm_D4"
<122s, 122s + 10*mfmsub_length .. 133s - 2*mfmsub_length>=>mfmsub
<128s>=>checkPoint,"startFo_D4"

<133s - mfmsub_length>=>checkPoint,"startFt_D5"
<133s>=>SatPulse(800ms)
<133s>=>mpulse
<133s + 400ms>=>checkPoint,"startFm_D5"
<133s + 800ms - mfmsub_length>=>checkPoint,"endFm_D5"
<134s, 134s + 10*mfmsub_length .. 140s - 2*mfmsub_length>=>mfmsub
<137s>=>checkPoint,"startFo_D5"

